version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ${DOCKERFILE_NAME:-Dockerfile}
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      - EXTERNAL_MOCK_URL=http://external-services-mock:8081/external
    depends_on:
      - db
      - external-services-mock
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  external-services-mock:
    build:
      context: ./external-services-mock
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M

volumes:
  postgres_data:
